export const currencies = [
    {
        symbol: '€',
        name: 'Euro',
        code: 'EUR',
        countryCode: 'EU',
    },
    {
        symbol: '$',
        name: 'US Dollar',
        code: 'USD',
        countryCode: 'US',
    },
    {
        symbol: '£',
        name: 'British Pound Sterling',
        code: 'GBP',
        countryCode: 'GB',
    },
    {
        symbol: 'Kč',
        name: 'Czech Republic Koruna',
        code: 'CZK',
        countryCode: 'CZ',
    },
    {
        symbol: 'zł',
        name: 'Polish Zloty',
        code: 'PLN',
        countryCode: 'PL',
    },
    {
        symbol: 'Ft',
        name: 'Hungarian Forint',
        code: 'HUF',
        countryCode: 'HU',
    },
    {
        symbol: 'CA$',
        name: 'Canadian Dollar',
        code: 'CAD',
        countryCode: 'CA',
    },
    {
        symbol: 'AED',
        name: 'United Arab Emirates Dirham',
        code: 'AED',
        countryCode: 'AE',
    },
    {
        symbol: 'Af',
        name: 'Afghan Afghani',
        code: 'AFN',
        countryCode: 'AF',
    },
    {
        symbol: 'ALL',
        name: 'Albanian Lek',
        code: 'ALL',
        countryCode: 'AL',
    },
    {
        symbol: 'AMD',
        name: 'Armenian Dram',
        code: 'AMD',
        countryCode: 'AM',
    },
    {
        symbol: 'AR$',
        name: 'Argentine Peso',
        code: 'ARS',
        countryCode: 'AR',
    },
    {
        symbol: 'AU$',
        name: 'Australian Dollar',
        code: 'AUD',
        countryCode: 'AU',
    },
    {
        symbol: 'man.',
        name: 'Azerbaijani Manat',
        code: 'AZN',
        countryCode: 'AZ',
    },
    {
        symbol: 'KM',
        name: 'Bosnia-Herzegovina Convertible Mark',
        code: 'BAM',
        countryCode: 'BA',
    },
    {
        symbol: 'Tk',
        name: 'Bangladeshi Taka',
        code: 'BDT',
        countryCode: 'BD',
    },
    {
        symbol: 'BGN',
        name: 'Bulgarian Lev',
        code: 'BGN',
        countryCode: 'BG',
    },
    {
        symbol: 'BD',
        name: 'Bahraini Dinar',
        code: 'BHD',
        countryCode: 'BH',
    },
    {
        symbol: 'FBu',
        name: 'Burundian Franc',
        code: 'BIF',
        countryCode: 'BI',
    },
    {
        symbol: 'BN$',
        name: 'Brunei Dollar',
        code: 'BND',
        countryCode: 'BN',
    },
    {
        symbol: 'Bs',
        name: 'Bolivian Boliviano',
        code: 'BOB',
        countryCode: 'BO',
    },
    {
        symbol: 'R$',
        name: 'Brazilian Real',
        code: 'BRL',
        countryCode: 'BR',
    },
    {
        symbol: 'BWP',
        name: 'Botswanan Pula',
        code: 'BWP',
        countryCode: 'BW',
    },
    {
        symbol: 'Br',
        name: 'Belarusian Ruble',
        code: 'BYN',
        countryCode: 'BY',
    },
    {
        symbol: 'BZ$',
        name: 'Belize Dollar',
        code: 'BZD',
        countryCode: 'BZ',
    },
    {
        symbol: 'CDF',
        name: 'Congolese Franc',
        code: 'CDF',
        countryCode: 'CD',
    },
    {
        symbol: 'CHF',
        name: 'Swiss Franc',
        code: 'CHF',
        countryCode: 'CH',
    },
    {
        symbol: 'CL$',
        name: 'Chilean Peso',
        code: 'CLP',
        countryCode: 'CL',
    },
    {
        symbol: 'CN¥',
        name: 'Chinese Yuan',
        code: 'CNY',
        countryCode: 'CN',
    },
    {
        symbol: 'CO$',
        name: 'Colombian Peso',
        code: 'COP',
        countryCode: 'CO',
    },
    {
        symbol: '₡',
        name: 'Costa Rican Colón',
        code: 'CRC',
        countryCode: 'CR',
    },
    {
        symbol: 'CV$',
        name: 'Cape Verdean Escudo',
        code: 'CVE',
        countryCode: 'CV',
    },
    {
        symbol: 'Fdj',
        name: 'Djiboutian Franc',
        code: 'DJF',
        countryCode: 'DJ',
    },
    {
        symbol: 'Dkr',
        name: 'Danish Krone',
        code: 'DKK',
        countryCode: 'GL',
    },
    {
        symbol: 'RD$',
        name: 'Dominican Peso',
        code: 'DOP',
        countryCode: 'DO',
    },
    {
        symbol: 'DA',
        name: 'Algerian Dinar',
        code: 'DZD',
        countryCode: 'DZ',
    },
    {
        symbol: 'EGP',
        name: 'Egyptian Pound',
        code: 'EGP',
        countryCode: 'EG',
    },
    {
        symbol: 'Nfk',
        name: 'Eritrean Nakfa',
        code: 'ERN',
        countryCode: 'ER',
    },
    {
        symbol: 'Br',
        name: 'Ethiopian Birr',
        code: 'ETB',
        countryCode: 'ET',
    },
    {
        symbol: 'GEL',
        name: 'Georgian Lari',
        code: 'GEL',
        countryCode: 'GE',
    },
    {
        symbol: 'GH₵',
        name: 'Ghanaian Cedi',
        code: 'GHS',
        countryCode: 'GH',
    },
    {
        symbol: 'FG',
        name: 'Guinean Franc',
        code: 'GNF',
        countryCode: 'GN',
    },
    {
        symbol: 'GTQ',
        name: 'Guatemalan Quetzal',
        code: 'GTQ',
        countryCode: 'GT',
    },
    {
        symbol: 'HK$',
        name: 'Hong Kong Dollar',
        code: 'HKD',
        countryCode: 'HK',
    },
    {
        symbol: 'HNL',
        name: 'Honduran Lempira',
        code: 'HNL',
        countryCode: 'HN',
    },
    {
        symbol: 'Rp',
        name: 'Indonesian Rupiah',
        code: 'IDR',
        countryCode: 'ID',
    },
    {
        symbol: '₪',
        name: 'Israeli New Sheqel',
        code: 'ILS',
        countryCode: 'IL',
    },
    {
        symbol: 'Rs',
        name: 'Indian Rupee',
        code: 'INR',
        countryCode: 'IN',
    },
    {
        symbol: 'IQD',
        name: 'Iraqi Dinar',
        code: 'IQD',
        countryCode: 'IQ',
    },
    {
        symbol: 'IRR',
        name: 'Iranian Rial',
        code: 'IRR',
        countryCode: 'IR',
    },
    {
        symbol: 'Ikr',
        name: 'Icelandic Króna',
        code: 'ISK',
        countryCode: 'IS',
    },
    {
        symbol: 'J$',
        name: 'Jamaican Dollar',
        code: 'JMD',
        countryCode: 'JM',
    },
    {
        symbol: 'JD',
        name: 'Jordanian Dinar',
        code: 'JOD',
        countryCode: 'JO',
    },
    {
        symbol: '¥',
        name: 'Japanese Yen',
        code: 'JPY',
        countryCode: 'JP',
    },
    {
        symbol: 'Ksh',
        name: 'Kenyan Shilling',
        code: 'KES',
        countryCode: 'KE',
    },
    {
        symbol: 'KHR',
        name: 'Cambodian Riel',
        code: 'KHR',
        countryCode: 'KH',
    },
    {
        symbol: 'CF',
        name: 'Comorian Franc',
        code: 'KMF',
        countryCode: 'KM',
    },
    {
        symbol: '₩',
        name: 'South Korean Won',
        code: 'KRW',
        countryCode: 'KR',
    },
    {
        symbol: 'KD',
        name: 'Kuwaiti Dinar',
        code: 'KWD',
        countryCode: 'KW',
    },
    {
        symbol: 'KZT',
        name: 'Kazakhstani Tenge',
        code: 'KZT',
        countryCode: 'KZ',
    },
    {
        symbol: 'L.L.',
        name: 'Lebanese Pound',
        code: 'LBP',
        countryCode: 'LB',
    },
    {
        symbol: 'SLRs',
        name: 'Sri Lankan Rupee',
        code: 'LKR',
        countryCode: 'LK',
    },
    {
        symbol: 'LD',
        name: 'Libyan Dinar',
        code: 'LYD',
        countryCode: 'LY',
    },
    {
        symbol: 'MAD',
        name: 'Moroccan Dirham',
        code: 'MAD',
        countryCode: 'MA',
    },
    {
        symbol: 'MDL',
        name: 'Moldovan Leu',
        code: 'MDL',
        countryCode: 'MD',
    },
    {
        symbol: 'MGA',
        name: 'Malagasy Ariary',
        code: 'MGA',
        countryCode: 'MG',
    },
    {
        symbol: 'MKD',
        name: 'Macedonian Denar',
        code: 'MKD',
        countryCode: 'MK',
    },
    {
        symbol: 'MMK',
        name: 'Myanma Kyat',
        code: 'MMK',
        countryCode: 'MM',
    },
    {
        symbol: 'MOP$',
        name: 'Macanese Pataca',
        code: 'MOP',
        countryCode: 'MO',
    },
    {
        symbol: 'MURs',
        name: 'Mauritian Rupee',
        code: 'MUR',
        countryCode: 'MU',
    },
    {
        symbol: 'MX$',
        name: 'Mexican Peso',
        code: 'MXN',
        countryCode: 'MX',
    },
    {
        symbol: 'RM',
        name: 'Malaysian Ringgit',
        code: 'MYR',
        countryCode: 'MY',
    },
    {
        symbol: 'MTn',
        name: 'Mozambican Metical',
        code: 'MZN',
        countryCode: 'MZ',
    },
    {
        symbol: 'N$',
        name: 'Namibian Dollar',
        code: 'NAD',
        countryCode: 'NA',
    },
    {
        symbol: '₦',
        name: 'Nigerian Naira',
        code: 'NGN',
        countryCode: 'NG',
    },
    {
        symbol: 'C$',
        name: 'Nicaraguan Córdoba',
        code: 'NIO',
        countryCode: 'NI',
    },
    {
        symbol: 'Nkr',
        name: 'Norwegian Krone',
        code: 'NOK',
        countryCode: 'SJ',
    },
    {
        symbol: 'NPRs',
        name: 'Nepalese Rupee',
        code: 'NPR',
        countryCode: 'NP',
    },
    {
        symbol: 'NZ$',
        name: 'New Zealand Dollar',
        code: 'NZD',
        countryCode: 'NZ',
    },
    {
        symbol: 'OMR',
        name: 'Omani Rial',
        code: 'OMR',
        countryCode: 'OM',
    },
    {
        symbol: 'B/.',
        name: 'Panamanian Balboa',
        code: 'PAB',
        countryCode: 'PA',
    },
    {
        symbol: 'S/.',
        name: 'Peruvian Nuevo Sol',
        code: 'PEN',
        countryCode: 'PE',
    },
    {
        symbol: '₱',
        name: 'Philippine Peso',
        code: 'PHP',
        countryCode: 'PH',
    },
    {
        symbol: 'PKRs',
        name: 'Pakistani Rupee',
        code: 'PKR',
        countryCode: 'PK',
    },
    {
        symbol: '₲',
        name: 'Paraguayan Guarani',
        code: 'PYG',
        countryCode: 'PY',
    },
    {
        symbol: 'QR',
        name: 'Qatari Rial',
        code: 'QAR',
        countryCode: 'QA',
    },
    {
        symbol: 'RON',
        name: 'Romanian Leu',
        code: 'RON',
        countryCode: 'RO',
    },
    {
        symbol: 'din.',
        name: 'Serbian Dinar',
        code: 'RSD',
        countryCode: 'RS',
    },
    {
        symbol: 'RUB',
        name: 'Russian Ruble',
        code: 'RUB',
        countryCode: 'RU',
    },
    {
        symbol: 'RWF',
        name: 'Rwandan Franc',
        code: 'RWF',
        countryCode: 'RW',
    },
    {
        symbol: 'SR',
        name: 'Saudi Riyal',
        code: 'SAR',
        countryCode: 'SA',
    },
    {
        symbol: 'SDG',
        name: 'Sudanese Pound',
        code: 'SDG',
        countryCode: 'SD',
    },
    {
        symbol: 'Skr',
        name: 'Swedish Krona',
        code: 'SEK',
        countryCode: 'SE',
    },
    {
        symbol: 'S$',
        name: 'Singapore Dollar',
        code: 'SGD',
        countryCode: 'SG',
    },
    {
        symbol: 'Ssh',
        name: 'Somali Shilling',
        code: 'SOS',
        countryCode: 'SO',
    },
    {
        symbol: 'SY£',
        name: 'Syrian Pound',
        code: 'SYP',
        countryCode: 'SY',
    },
    {
        symbol: '฿',
        name: 'Thai Baht',
        code: 'THB',
        countryCode: 'TH',
    },
    {
        symbol: 'DT',
        name: 'Tunisian Dinar',
        code: 'TND',
        countryCode: 'TN',
    },
    {
        symbol: 'T$',
        name: 'Tongan Paʻanga',
        code: 'TOP',
        countryCode: 'TO',
    },
    {
        symbol: 'TL',
        name: 'Turkish Lira',
        code: 'TRY',
        countryCode: 'TR',
    },
    {
        symbol: 'TT$',
        name: 'Trinidad and Tobago Dollar',
        code: 'TTD',
        countryCode: 'TT',
    },
    {
        symbol: 'NT$',
        name: 'New Taiwan Dollar',
        code: 'TWD',
        countryCode: 'TW',
    },
    {
        symbol: 'TSh',
        name: 'Tanzanian Shilling',
        code: 'TZS',
        countryCode: 'TZ',
    },
    {
        symbol: '₴',
        name: 'Ukrainian Hryvnia',
        code: 'UAH',
        countryCode: 'UA',
    },
    {
        symbol: 'USh',
        name: 'Ugandan Shilling',
        code: 'UGX',
        countryCode: 'UG',
    },
    {
        symbol: '$U',
        name: 'Uruguayan Peso',
        code: 'UYU',
        countryCode: 'UY',
    },
    {
        symbol: 'UZS',
        name: 'Uzbekistan Som',
        code: 'UZS',
        countryCode: 'UZ',
    },
    {
        symbol: 'Bs.F.',
        name: 'Venezuelan Bolívar',
        code: 'VEF',
        countryCode: 'VE',
    },
    {
        symbol: '₫',
        name: 'Vietnamese Dong',
        code: 'VND',
        countryCode: 'VN',
    },
    {
        symbol: 'FCFA',
        name: 'CFA Franc BEAC',
        code: 'XAF',
        countryCode: 'TD',
    },
    {
        symbol: 'CFA',
        name: 'CFA Franc BCEAO',
        code: 'XOF',
        countryCode: 'TG',
    },
    {
        symbol: 'YR',
        name: 'Yemeni Rial',
        code: 'YER',
        countryCode: 'YE',
    },
    {
        symbol: 'R',
        name: 'South African Rand',
        code: 'ZAR',
        countryCode: 'ZA',
    },
    {
        symbol: 'ZK',
        name: 'Zambian Kwacha',
        code: 'ZMK',
        countryCode: 'ZM',
    },
    {
        symbol: 'ZWL$',
        name: 'Zimbabwean Dollar',
        code: 'ZWL',
        countryCode: 'ZW',
    },
]
